# Makefile for LRU-WT tree.


THISTREE:=$(shell cd ../../..; pwd)
include $(THISTREE)/make.conf

extension: m3sources	# make.extension has the rule to build m3sources

install: extension 

include ../../make.extension

