%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% HISTORY
% 06-Oct-96  Robert Grimm (rgrimm) at the University of Washington
%       TcpOsf and UdpOsf are now exported from the Plexus domain
%
% 27-Feb-96  Marc Fiuczynski (mef) at the University of Washington
%	Both the HTTP and Scale module are obsolete.
%
% 08-Feb-96  Charles Garrett (garrett) at the University of Washington
%	These modules are now hidden. Change module to Module to export
%	 the interfaces from the Plexus domain.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

overridepath = [ THISTREE , FULLTREE ]
DomainImport("SpinPublic","kernel","spincore",overridepath)
DomainImport("SpinTrusted","kernel","spincore",overridepath)
DomainImport ("Shell","user/shell","shellcore",overridepath)
DomainImport ("SpinUnixRunTime","user/urt","urtcore",overridepath)
DomainImport ("SpinUnixNet","user/urt","net",overridepath)
DomainImport ("NetDev","user/dev","netdev",overridepath)
DomainImport ("Device","user/dev","devcore",overridepath)
importfrompath ("user/net","plexus",overridepath)

DomainImport ("IpServer","user/net","ip",overridepath)
DomainImport ("TcpServer","user/net","tcp",overridepath)
DomainImport ("IcmpServer","user/net","icmp",overridepath)
DomainImport ("UdpServer","user/net","udp",overridepath)
DomainImport ("IpClient","user/net","ipClient",overridepath)
DomainImport ("NetDb","user/net","dns",overridepath)

Package("OsfNetEmulation")

module ("Key")
interface ("Port")
CommandModule ("TcpOsf")
table  ("TcpOsf", "Key", "Port")
CommandModule ("UdpOsf")
table  ("UdpOsf", "Key", "Port")
module ("IcmpOsf")

linkmodule("OsfNetEmulation")
Module ("OsfNetEmulation")

Extension({})
