% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Nov 22 07:56:45 PST 1994 by kalsow
%      modified on Mon May 24 15:12:25 PDT 1993 by muller

% m3_option("-X6@-O@")  -- not safe on alpha yet...
% # m3_option("-keep") # keeps m3 ir and assembly intermediate files

%
% HISTORY
% 13-Nov-95  Wilson Hsieh (whsieh) at the University of Washington
%	commented out unused modules
%

import (libm3)

include_dir (OS_TYPE)

Module ("Target")
Module ("TargetMap")
Module ("TInt")
Module ("TWord")
Module ("TFloat")

Module ("M3FP")
Module ("M3Buf")
Module ("M3ID")
Module ("M3Timers")
Module ("M3File")

Module ("M3CG")
Interface ("M3CG_Ops")

Module ("M3CG_Check")

% these do not appear to be used WCH
%Module ("M3CG_Clean")
%Module ("M3CG_Rd")

Module ("M3CG_Wr")
Module ("M3RT")

Library ("m3middle")


