# HISTORY
# 29-Apr-96  Emin Gun Sirer (egs) at the University of Washington
#	Whisted.
#

overridepath = [ THISTREE , FULLTREE ]
DomainImport("SpinPublic","kernel","spincore",overridepath)
DomainImport("SpinTrusted","kernel","spincore",overridepath)
DomainImport("Shell","user/shell","shellcore",overridepath)

CommandModule("Threat")

Extension({})

