% Copyright (C) 1993, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Tue Jan 24 08:32:45 PST 1995 by kalsow 
%      modified on Fri Apr 30 11:31:44 PDT 1993 by mjordan

% HISTORY
% 16-Jul-97  Tian Fung Lim (tian) at the University of Washington
%	Added writebarrier platform

% 30-Jan-97  Wilson Hsieh (whsieh) at the University of Washington
%	TARGET -> BASETARGET
%
% 13-Aug-96  Frederick Gray (fgray) at the University of Washington
%	Added IX86_SPIN target.
%
% 05-May-96  Charles Garrett (garrett) at the University of Washington
% 	Handle both profiled and unprofiled targets. The profiled
%	version has the target ALPHA_SPIN_PROF.
%
% 22-Feb-96  Charles Garrett (garrett) at the University of Washington
%	Added ALPHA_SPIN target.

readonly EXCEPTION_IMPL = {
  "ALPHA_OSF"  : "ex_frame",  % does not have a working stack walker
  "ALPHA_SPIN" : "ex_frame",  % does not have a working stack walker
  "AIX386"     : "ex_frame",
  "AP3000"     : "ex_frame",
  "ARM"        : "ex_frame",
  "DS3100"     : "ex_stack",  % has a working stack walker
  "FreeBSD"    : "ex_frame",
  "FreeBSD2"   : "ex_frame",
  "HP300"      : "ex_frame",
  "HPPA"       : "ex_frame",
  "IBMR2"      : "ex_frame",
  "IBMRT"      : "ex_frame",
  "IRIX5"      : "ex_frame",
  "LINUX"      : "ex_frame",
  "LINUXELF"   : "ex_frame",
  "IX86_SPIN" : "ex_frame",
  "NEXT"       : "ex_frame",
  "NT386"      : "ex_frame",
  "OKI"        : "ex_frame",
  "SEQUENT"    : "ex_frame",
  "SOLgnu"     : "ex_frame",
  "SOLsun"     : "ex_frame",
  "SPARC"      : "ex_frame",
  "SUN3"       : "ex_frame",
  "SUN386"     : "ex_frame",
  "UMAX"       : "ex_frame",
  "VAX"        : "ex_frame"
}

include_dir (gc_stats)

if equal(TARGET,"ALPHA_SPIN_SYSTEM")
    include_dir(commonsystem)
else
    include_dir(common)
end
include_dir(OS_TYPE)
include_dir(BASETARGET)
include_dir(EXCEPTION_IMPL{BASETARGET})

if equal(WRITEBARRIER, "TRUE") 
	include_dir("gc_tm")	
else
if equal(REFCOUNT, "TRUE")
	include_dir("gc_rc")
	include_dir("gc_mas")
else
	include_dir("gc_copy")
	% include_dir("gc_tm")
end
end

