#
# Copyright 1994, University of Washington
# All rights reserved.
# See COPYRIGHT file for a full description
#
#
# HISTORY
# 19-Mar-96  Stefan Savage (savage) at the University of Washington
#       Created.
#
# 

overridepath = [ THISTREE , FULLTREE ]
DomainImport("SpinPublic","kernel","spincore",overridepath)
DomainImport("SpinTrusted","kernel","spincore",overridepath)
DomainImport("VMCore","user/vm","vmcore",overridepath)

Package("Space")

Module("Space")

Extension({})
