#
# Copyright 1995, University of Washington
# All rights reserved.
# See COPYRIGHT file for a full description
#
# HISTORY
#
# 06-Aug-97  Robert Grimm (rgrimm) at the University of Washington
#	Created.
#


THISTREE:=$(shell cd ../../../..; pwd)
include $(THISTREE)/make.conf

all:	m3sources

include ../../../make.extension

