%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% HISTORY
% 08-Feb-96  Charles Garrett (garrett) at the University of Washington
%	These modules are now hidden. Change module to Module to export
%	 the interfaces from the Plexus domain.
%

interface ("AtmPktFormat")
module ("AtmPacket")
module ("Atm") 
module ("AtmTrusted")
module ("AtmServer")
