#
# Copyright 1995, University of Washington
# All rights reserved.
# See COPYRIGHT file for a full description
#
# 15-Jul-96  Przemek Pardyak (pardy) at the University of Washington
#	Created.
#


THISTREE:=$(shell cd ../..; pwd)
include $(THISTREE)/make.conf

all:	m3sources

install: all

include ../make.extension

