% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Thu Aug 26 11:55:48 PDT 1993 by kalsow
%      modified on Mon Apr 26 13:38:32 PDT 1993 by mcjones

#
# HISTORY
# 12-Jun-97  Wilson Hsieh (whsieh) at the University of Washington
#	export Addr
#
#

Generic_module(Utable)
Generic_module(ArraySort)

template (utable)
template (arraysort)

Module (Addr)
module (Int)
