rcp -r flimflam:/proj/m3/pkg/win32 .
rcp -r flimflam:/proj/m3/pkg/Csupport-ip .
rcp -r flimflam:/proj/m3/pkg/C-ip .
rcp -r flimflam:/proj/m3/pkg/runtime-ip .
rcp -r flimflam:/proj/m3/pkg/random-ip .
rcp -r flimflam:/proj/m3/pkg/float-ip .
rcp -r flimflam:/proj/m3/pkg/time-ip .
rcp -r flimflam:/proj/m3/pkg/os-ip .
rcp -r flimflam:/proj/m3/pkg/thread-ip .
rcp -r flimflam:/proj/m3/pkg/uid-ip .
rcp -r flimflam:/proj/m3/pkg/smallio-ip .
rcp -r flimflam:/proj/m3/pkg/perftool-ip .
rcp -r flimflam:/proj/m3/pkg/convert .
rcp -r flimflam:/proj/m3/pkg/fingerprint-ip .
rcp -r flimflam:/proj/m3/pkg/fmt .
rcp -r flimflam:/proj/m3/pkg/list-ip .
rcp -r flimflam:/proj/m3/pkg/sx-ip .
rcp -r flimflam:/proj/m3/pkg/main .
rcp -r flimflam:/proj/m3/pkg/rw-ip .
rcp -r flimflam:/proj/m3/pkg/scan .
rcp -r flimflam:/proj/m3/pkg/text-ip .
rcp -r flimflam:/proj/m3/pkg/types-ip .
rcp -r flimflam:/proj/m3/pkg/arith .
rcp -r flimflam:/proj/m3/pkg/geometry-ip .
rcp -r flimflam:/proj/m3/pkg/statistics .
rcp -r flimflam:/proj/m3/pkg/formatter-ip .
rcp -r flimflam:/proj/m3/pkg/params-ip .
rcp -r flimflam:/proj/m3/pkg/property .
rcp -r flimflam:/proj/m3/pkg/atom-ip .
rcp -r flimflam:/proj/m3/pkg/table-ip .
rcp -r flimflam:/proj/m3/pkg/sortedtable-ip .
rcp -r flimflam:/proj/m3/pkg/sort-ip .
rcp -r flimflam:/proj/m3/pkg/sequence-ip .
rcp -r flimflam:/proj/m3/pkg/pickle-ip .
rcp -r flimflam:/proj/m3/pkg/word .
rcp -r flimflam:/proj/m3/pkg/etimer-ip .
rcp -r flimflam:/proj/m3/pkg/weakref-ip .
rcp -r flimflam:/proj/m3/pkg/bundleintf .
