% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% Last modified on Fri Aug 13 09:55:30 PDT 1993 by kalsow

% HISTORY
% 30-Jan-97  Wilson Hsieh (whsieh) at the University of Washington
%	TARGET -> BASETARGET
%
% 05-May-96  Charles Garrett (garrett) at the University of Washington
% 	Handle both profiled and unprofiled targets.

include_dir(Common)
include_dir(BASETARGET)
