#
# rmdir makefile 
#

overridepath = [ THISTREE , FULLTREE ]

DomainImport("SpinPublic","kernel","spincore",overridepath)
DomainImport("SpinTrusted","kernel","spincore",overridepath)
DomainImport("Shell","user/shell","shellcore",overridepath)
DomainImport("Device","user/dev","devcore",overridepath)
DomainImport("FileSystem","user/fs","fscore",overridepath)
DomainImport("Segment","user/fs/lfs","segment",overridepath)
#DomainImport("SegBuffer","user/fs/lfs","buffer",overridepath)
DomainImport("LFSCore","user/fs/lfs","lfscore",overridepath)

Package("RmDir")
CommandModule("RmDir")
Extension({})


