#
# imaptest makefile 
#

overridepath = [ THISTREE , FULLTREE ]

DomainImport("SpinPublic","kernel","spincore",overridepath)
DomainImport("SpinTrusted","kernel","spincore",overridepath)
DomainImport("Shell","user/shell","shellcore",overridepath)
DomainImport("Device","user/dev","devcore",overridepath)
DomainImport("Segment","user/fs/lfs","segment",overridepath)
DomainImport("Extent","user/dev","extent",overridepath)
DomainImport("FileSystem","user/fs","fscore",overridepath)
DomainImport("LFS","user/fs","lfs",overridepath)
DomainImport("LFSCore","user/fs/lfs","lfscore",overridepath)

Package("MakeFs")
CommandModule("MakeFs")
Extension({})


