MODULE DhtIP4;
IMPORT Word;

PROCEDURE Equal(READONLY pa1: T; READONLY pa2: T): BOOLEAN =
  BEGIN
    RETURN pa1 = pa2;
  END Equal;

PROCEDURE Hash (READONLY pa: T): Word.T = 
  BEGIN
    RETURN pa;
  END Hash;

BEGIN
END DhtIP4.
