% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.

% File: m3makefile
% Last modified on Mon Jun 21 09:49:42 PDT 1993 by kalsow
%      modified on Fri Feb  7 00:38:19 PST 1992 by muller

%
% HISTORY
% 07-May-96  Wilson Hsieh (whsieh) at the University of Washington
%	move Procany to spin dir
%
% 15-Apr-96  Wilson Hsieh (whsieh) at the University of Washington
%	added Procany module
%
%

module (Addr)
module (Bool)
module (BuiltinTypes)
module (CChar)
module (Card)
module (EReel)
module (ErrType)
module (Int)
module (LReel)
module (Mutex)
module (Null)
module (ObjectAdr)
module (ObjectRef)
module (Reel)
module (Reff)
module (Textt)
