#
# Copyright 1997, University of Washington
# All rights reserved.
# See COPYRIGHT file for a full description

THISTREE:=$(shell cd ../..; pwd)
include $(THISTREE)/make.conf

all:	m3sources

install: all

include ../make.extension

