#include <stdio.h>
extern void *sigcode;
extern int szsigcode;

main(int argc, char **argv)
{
    int i;
    FILE *of;
    char file_name[128];
    unsigned char *sigcodex = (unsigned char*)&sigcode;
    strcpy(file_name, argv[1]);

    of = fopen(file_name, "w");
    if (of == 0) {
	perror(file_name);
	exit(1);
    }
    fprintf(of, "(* This file is created by gensigcode. Do not edit this file*)\n");
    fprintf(of, "INTERFACE SigTramp;\n");
    fprintf(of, "CONST Code = ARRAY [0..%d] OF CHAR {\n", szsigcode-1);
    for (i = 0; i < szsigcode; i++) {
	fprintf(of, " '\\%03o'", sigcodex[i]);
	if (i < szsigcode-1) {
	    fprintf(of, ", ");
	}
    }
    fprintf(of, "};\n");
    fprintf(of, "END SigTramp.\n");
    fclose(of);
}
