#
# Copyright 1995, University of Washington
# All rights reserved.
# See COPYRIGHT file for a full description
#

#
# HISTORY
% 30-Jan-97  Wilson Hsieh (whsieh) at the University of Washington
%	TARGET -> BASETARGET
%
# 28-Mar-96  Przemek Pardyak (pardy) at the University of Washington
#	Converted to new build environment.
#
# 29-Nov-95  Przemek Pardyak (pardy) at the University of Washington
#	Created
#
#


m3_option("-X6@-fno-common@")
m3_option("-zG@-g3@")
overridepath = [ THISTREE , FULLTREE ]
DomainImport("SpinPublic","kernel","spincore",overridepath)
DomainImport("SpinTrusted","kernel","spincore",overridepath)
DomainImport ("Shell","user/shell","shellcore",overridepath)
DomainImport ("Regress","user/shell","regress",overridepath)

include_dir(BASETARGET)

Extension({})

