% Copyright ("C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Wed May 25 15:20:16 PDT 1994 by kalsow 
%      modified on Wed May 25 14:44:43 PDT 1994 by detlefs
%      modified on Wed Jun  2 15:25:51 PDT 1993 by muller
%      modified on Fri May  7 22:32:22 PDT 1993 by mjordan
%      modified on Tue Apr 20 14:35:55 PDT 1993 by mcjones
%      modified on Sun Feb 21 14:07:29 PST 1993 by jdd

#
# HISTORY
# 27-Jan-97  Wilson Hsieh (whsieh) at the University of Washington
#	added RTCollectorSpin
#
# 14-Nov-96  Przemek Pardyak (pardy) at the University of Washington
#	Added RTHeapPages.
#


Module ("RTHooks")
Module ("RTHeap")
Module ("RTHeapPages")
Module ("RTHeapMap")
Module ("RTIO")
Module ("RTLinker")
Module ("RTMapOp")
Module ("RTMisc")
Module ("RTModule")
Module ("RTParams")
Module ("RTProcedure")
Module ("RTProcess")
Module ("RTType")
Module ("RTTypeMap")
Module ("RTutils")
Module ("RTHeapRep")
Module ("RTHeapTrace")
Module ("RTHeapStats")
Module ("RTHisto")

Interface ("RTHeapDep")
Interface ("RTArgs")
Interface ("RTException")
Interface ("RTProcedureSRC")
Interface ("RTHeapInfo")
Interface ("RTOS")
Interface ("RTSignal")
Interface ("RTThreadInit")
Interface ("RTTypeSRC")
interface ("RTWeakRef")

Interface ("RTHeapDebug")
Interface ("RTAllocator")
Interface ("RTCollector")
implementation ("RT0")

Module    ("RTProcDesc")
Interface ("RTProcDescF")
Utable (ProcDesc, Addr, RTProcDescF)

c_source ("RTBuiltin")
pgm_source ("RTBuiltin.m3x")



