% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
# HISTORY
# 21-Apr-96  David Becker (becker) at the University of Washington
#       changed overrides to be absolute path so make machine can pick
#	up the library dependencies
#
% File: m3makefile
% Last modified on Wed Aug  3 13:58:41 PDT 1994 by kalsow
%      modified on Wed May 26 11:51:10 PDT 1993 by muller

import (libm3)

COMPILERTREE=THISTREE & "/local/m3"
override ("m3middle", COMPILERTREE)
import (m3middle)

Module (Mx)
Module (MxIn)
Module (MxOut)
Module (MxMerge)
Module (MxCheck)
Module (MxGen)
Module (MxVS)

module (MxRep)
module (MxMap)
module (MxSet)
module (MxVSSet)
module (MxIO)

Library (m3link)

