#
# Copyright 1995, University of Washington
# All rights reserved.
# See COPYRIGHT file for a full description
#
# HISTORY
# 24-Sep-96  Marc Fiuczynski (mef) at the University of Washington
#	created.
#

RegressionModule("BitField")
