overridepath = [ THISTREE , FULLTREE ]
DomainImport("SpinPublic","kernel","spincore",overridepath)
DomainImport("SpinTrusted","kernel","spincore",overridepath)
DomainImport ("Shell","user/shell","shellcore",overridepath)

CommandModule("Nanny")
Extension({})

