
%
% HISTORY
% 30-Jan-97  Wilson Hsieh (whsieh) at the University of Washington
%	TARGET -> BASETARGET
%

overridepath = [ THISTREE , FULLTREE ]
DomainImport("SpinPublic","kernel","spincore",overridepath)
DomainImport("SpinTrusted","kernel","spincore",overridepath)
DomainImport("SecurityPublic","kernel","spincore",overridepath)
DomainImport("SecurityTrusted","kernel","spincore",overridepath)
	% fix me!
DomainImport("Device","user/dev","devcore",overridepath)
DomainImport("VMCore","user/vm","vmcore",overridepath)
DomainImport("Space","user/vm","space",overridepath)
DomainImport("Console","user/dev","console",overridepath)

Package("UserSpaceThread")
Module("UserSpaceThread")
interface("USTFPU")

include_dir(BASETARGET)

Extension({})
