#
# Makefile for init.
#
# HISTORY
# 22-Mar-97  Tsutomu Owa (owa) at the University of Washington
#	Whisted.

THISTREE:=$(shell cd ../..; pwd)
include $(THISTREE)/make.conf

extension: m3sources

install: extension
include ../make.extension

