% Copyright (C) 1994, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
% Last modified on Mon Nov 21 11:29:15 PST 1994 by kalsow
%      modified on Mon Dec 14 19:59:03 PST 1992 by jdd
%      modified on Wed May 20 17:21:29 PDT 1992 by muller

#
# HISTORY
# 10-Feb-97  Wilson Hsieh (whsieh) at the University of Washington
#	added RTCounting.c
#
# 14-Nov-96  Przemek Pardyak (pardy) at the University of Washington
#	Added RTOSMachine.m3
#
# 14-Oct-96  Przemek Pardyak (pardy) at the University of Washington
#	Moved RTHeapDep.m3 to spincore.
#
# 13-Aug-96  Frederick Gray (fgray) at the University of Washington
#	Made RTOSMachine.i3, RTMachineHeapTrace.i3, and RTMachineHeapTrace.m3 
#	machine-dependent.
#

Module         ("RTMachine")
Interface      ("RTMachineExtern")
implementation ("RTSignal")
implementation ("RTThread")
c_source       ("RTThreadC")

Module ("RTMachineHeapTrace")
c_source ("RTCounting")
%% s_source ("RTStackASM")

Module ("RTOSMachine")

Interface      ("RTMachineCollectorExtern")