#####################################################################
# Copyright 1994, 1995 University of Washington
# All rights reserved.
# See COPYRIGHT file for a full description
#
# HISTORY
#####################################################################

c_source("SpinProgram")
