#
# Copyright 1995, University of Washington
# All rights reserved.
# See COPYRIGHT file for a full description
#
# HISTORY
# 28-Mar-96  Przemek Pardyak (pardy) at the University of Washington
#	Converted to new build environment.
#
# 22-Feb-96  Charles Garrett (garrett) at the University of Washington
#	Changed ALPHA_OSF to ALPHA_SPIN.
#
# 4-Jan-96  Przemek Pardyak (pardy) at the University of Washington
#	Created.
#


THISTREE:=$(shell cd ../../../..; pwd)
include $(THISTREE)/make.conf

all:	m3sources

include ../../../make.extension


