% Copyright (C) 1992, Digital Equipment Corporation
% All rights reserved.
% See the file COPYRIGHT for a full description.
%
# HISTORY
# 21-Apr-96  David Becker (becker) at the University of Washington
#       changed overrides to be absolute path so make machine can pick
#	up the library dependencies
#
% Last modified on Thu Jan 26 10:34:43 PST 1995 by kalsow
%      modified on Tue May 25 14:48:19 PDT 1993 by muller

m3_option ("-times")
m3_option ("-g")
% m3_option ("-X6@-O@")  -- not safe on alpha yet...
% m3_option("-keep") # keeps m3 ir and assembly intermediate files
% m3_option ("-commands")

import (libm3)

% BACKEND
COMPILERTREE=THISTREE & "/local/m3"
override ("m3middle", COMPILERTREE)
import (m3middle)

% FRONTEND
include_dir (spin)
include_dir (builtinOps)
include_dir (builtinWord)
include_dir (builtinTypes)
include_dir (exprs)
include_dir (misc)
include_dir (stmts)
include_dir (types)
include_dir (values)

Library (m3front)




